sudo: required
services:
  - docker

before_install:
  - docker build -t roshanwankhade/docker-react -f Dockerfile.dev .

script:
  - docker run roshanwankhade/docker-react npm run test -- --coverage
